### PR TITLE
Base Project Implementation

### PR DESCRIPTION
**Pull request by jainal09**
Hi, 
I have created a Base repository with all the initial codes such as dockerfile, docker-compose.yaml, setting up Mongo DB, setting up celery, building indexers, creating models, creating a API endpoint for search through elastic search, requirements.txt and basic project structure folders

### CODE REVIEW

**Comment by vivonk** [comment]
Overall work done is good, but right now project is in begin mode so base architecture will be designed by someone from inside team or GSoC student. But your design is also considerable. Once GSoC begins, someone will update you on this @jainal09

**Comment by jainal09** [comment]
Yeh sure and this is a work done as a contribution for GSOC 2020 proposal of mine on crawlerX. So kindly consider it when you review my proposal.

**Comment by PratikDhanave** [comment]
great work

**Comment by jainal09** [comment]
Thanks!

**Comment by jainal09** [comment]
Also, what's everyone's opinion on using **Django** over **flask**?. I have selected Django in these commits as from my previous experiences using Django with celery and elastic search is quite a good experience as compared to flask. Also, the library features, support, docs and tutorials of Django with celery and Elastic Search are quite nice actually.

So, drop in your opinions over this, if its a good or bad decision.

**Comment by PratikDhanave** [comment]
Go Programming language  will be right choice as Distributed scalable application with gin framework.

**Comment by PratikDhanave** [comment]
@jainal09 https://tour.golang.org/  https://github.com/gin-gonic/gin

**Comment by jainal09** [comment]
Oh yeah go also a Great choice. But isn't it compulsory to stick according to the idealist of crawlerX that specifies to do it in flask or can it be changed ? I don't have any clue just asking is there any compulsion?
Because, I thats why choose django as its still in python. But I must say gin and go is also a good choice its light weight ,very fast, there is a gocelery lib and go elastic search client. So it will be a good choice.

**Comment by jainal09** [comment]
There is also colly - https://github.com/gocolly/colly
Its very efficient webscrapping framework in Go.

**Comment by PratikDhanave** [comment]
great

**Pull request closed without merging**
